### ISSUE TITLE
Strategies missing.

### ISSUE THREAD

**Issue by yuvarajagna** [etimberg/pycircuitbreaker#3]
## Environment

* pycircuitbreaker version:0.2.0
* Python version:3.7
* Link to your project:

Got [ERROR] Runtime.ImportModuleError: Unable to import module : No module named 'pycircuitbreaker.strategies'

when installing pip3 install --target ./ pycircuitbreaker i couldn't see the strategies folder inside pycircuitbreaker.

**Comment by etimberg** [comment]
Thanks for reporting this @yuvarajagna. A fixed version was released as v0.2.1
