### ISSUE TITLE
Circuit Breakers registry

### ISSUE THREAD

**Issue by migibert** [etimberg/pycircuitbreaker#9]
### Feature Proposal
It could be useful to propose a registry that would:
- expose all the registered circuit breakers
- retrieve circuits by state (open, half open, closed)
- let the decorator use the registry to create or retrieve a circuit breaker

It is quite similar to what exists in the [circuitbreaker](https://pypi.org/project/circuitbreaker/) library.

### Feature Use Case
I see two usecases that would be unlocked with this feature:
- Exposing the circuit breakers states on the readiness probe of an application
- Use the same circuit breaker for some functions (if they all rely on calling the same external dependency)

## Possible Implementation
I can propose a PR to implement that solution but I wanted to discuss the interest of the feature before coding something :)

**Comment by etimberg** [comment]
This sounds like a good idea to me. Feel free to send a PR with an initial implementation 😄
